# Python CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: install dependencies
          command: |
            poetry install 

      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ checksum "poetry.lock" }}

      - run: 
          name: run tests
          command: |
            poetry run pytest

      - run:
          name: run flake8
          command: |
            poetry run flake8

      - run:
          name: run mypy
          command: |
            poetry run mypy ./ --ignore-missing
